### ISSUE TITLE
More notifications

### ISSUE THREAD

**Issue by Eldenroot** [lukasamd/MyBB-Mod_Notify#2]
Hi,
I installed your plugin yesterday, it is really nice addition (before I used a pack with extra notifications from Shade for MyAlerts... but many users on my board dont like MyAlerts system and dont use that).

I would like to see more notification options, for me the most important is:
- if someone report a post/thread and moderator/admin read the report -> send a PM to the user who reported the post about that
- send PM to user who has a birthday
-moderate an user posting activity;
- suspend an user's signature;
- change an user's username;
- change an user's signature;

**Comment by lukasamd** [comment]
Hello,
it isn't myalerts alternative, so I will not add PM about birthday.
Suspend signature or change signature / username - it's difficult, because moderator can make many changes on edit user page and we can't determine, what he did. 

PM about report and read... I will check this, it may be possible.

**Comment by Eldenroot** [comment]
Hi,
about birthday, I mean something like this:
https://mods.mybb.com/view/its-my-birthday

For reports - you can take inspiration from here:
https://mods.mybb.com/view/thanks-for-the-report

**Comment by lukasamd** [comment]
Sorry, it's "moderator notification", not birthay, I will not add this.

**Comment by Eldenroot** [comment]
IT is fine, just had an idea :)
